name: CD.docker

on:
  push:
    branches: [ develop ]

jobs:
  build_CD:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t impejonathan/carter -f ../mobivia/Dockerfile ../mobivia

    - name: Push Docker Image
      run: |
        docker push impejonathan/carter
